import pandas as pd
import joblib
import numpy as np
from tensorflow.keras.models import load_model

# =====================
# LOAD DATA
# =====================
df = pd.read_csv("Dataset/NASA Bawean Hourly Full.csv")

# =====================
# FEATURE ENGINEERING
# =====================
for lag in [1,2,3,24]:
    df[f"lag{lag}"] = df["WS10M"].shift(lag)

df["mean3"] = df["WS10M"].rolling(3).mean()
df["mean24"] = df["WS10M"].rolling(24).mean()

df = df.dropna()

# =====================
# LOAD MODEL
# =====================
gbr = joblib.load("models/gbr.pkl")
xgb = joblib.load("models/xgb.pkl")
knn = joblib.load("models/knn.pkl")
scaler = joblib.load("models/scaler.pkl")

# =====================
# PREP DATA
# =====================
X = df.drop("WS10M", axis=1).values

# =====================
# PREDIKSI
# =====================
df["GBR"] = gbr.predict(X)
df["XGB"] = xgb.predict(X)
df["KNN"] = knn.predict(scaler.transform(X))

# =====================
# HEADER NASA STYLE
# =====================
header = [
    "-BEGIN HEADER-",
    "Custom Prediction Data",
    "Source: Model Comparison (GBR, XGB, KNN)",
    "Location: Generated by Flask App",
    "Parameter(s):",
    "WS10M = Actual Wind Speed",
    "GBR = Gradient Boosting Result",
    "XGB = XGBoost Result",
    "KNN = KNN Result",
    "-END HEADER-"
]

# =====================
# SAVE CSV
# =====================
with open("hasil_prediksi_full.csv", "w") as f:
    for line in header:
        f.write(line + "\n")

df.to_csv("hasil_prediksi_full.csv", mode="a", index=False)

print("✅ CSV berhasil dibuat!")